#  æ ¼å¼åŒ–å­—ç¬¦ä¸²
#  æ”¯æŒå˜é‡:
#  {CpuUsage}   CPUä½¿ç”¨ç‡
#  {MemoryUsage}   å†…å­˜ä½¿ç”¨ç‡
#  {DiskUsage}   ç£ç›˜ä½¿ç”¨ç‡
formatString: "ğŸ–¥ CPUä½¿ç”¨ç‡: {CpuUsage}\\nğŸ’¾ å†…å­˜ä½¿ç”¨: {MemoryUsage}\\nğŸ’½ ç£ç›˜ç©ºé—´: {DiskUsage}"